# Generated by Django 5.0.6 on 2024-06-15 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('is_complete', models.BooleanField(verbose_name=False)),
                ('created_date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
    ]
